### ISSUE TITLE
Issues with apache2 and vhost

### ISSUE THREAD

**Issue by janette** [NuCivic/ansible-dev-vm#22]
**apache2 problem**

```
Invalid command 'Header', perhaps misspelled or defined by a module not included in the server configuration
Action 'configtest' failed.
The Apache error log may have more information.
```

**solution**
`sudo  a2enmod headers`

**vhost problem**
do we use drush aliases anymore? or buck? I've been using https://github.com/NuCivic/vhost
but the resulting file needs to be updated with the '.conf' to work on 14.04

`mv mysite.local mysite.local.conf`

**Comment by acouch** [comment]
Looks like this was fixed: https://github.com/NuCivic/ansible-dev-vm/pull/39
