### ISSUE TITLE
Terminus is not installed

### ISSUE THREAD

**Issue by janette** [NuCivic/ansible-dev-vm#23]
https://github.com/pantheon-systems/cli

**Comment by acouch** [comment]
It should be.

**Comment by acouch** [comment]
```
TASK: [nucivic | Install Terminus] ********************************************
skipping: [nucvicdev]
```

Not sure why it is skipping.

**Comment by acouch** [comment]
@janette can you try and re-run `vagrant provision` once more? Twice did the trick for me.

**Comment by janette** [comment]
I just installed it manually
