### ISSUE TITLE
Can't delete DKAN webroot from inside VM

### ISSUE THREAD

**Issue by dafeder** [NuCivic/ansible-dev-vm#40]
I'm not sure if this is problem with the VM exactly, but deleting the built webroot of a DKAN instance seems to be impossible inside the VM, on both virtualbox and vmware:

```
vagrant@local:/var/www/dkan$ sudo rm -rf webroot
rm: cannot remove ‘webroot/sites/default/default.settings.php’: Permission denied
rm: cannot remove ‘webroot/sites/default/files’: Permission denied
rm: cannot remove ‘webroot/sites/default/settings.php’: Permission denied
vagrant@local:/var/www/dkan$
```

I need to `rm` it as sudo from my mac to get rid of it.

**Comment by acouch** [comment]
I think this is a quirk with the NSF mount.

You can fix this inside the vm by `chmod 777 webroot/sites/default` and then `rm`

Not sure if there is a better solution.

**Comment by frankcarey** [comment]
It's not just NFS, the Drupal installer changes these permissions, requiring a chmod before removing (even with sudo rm -rf)  The new ahoy script automatically does this for you when rebuilding drupal, so marking this fixed.
